### ISSUE TITLE
Get and set uncertainty property (Visit/Discharge/Discharge section main/Manual gauging

### ISSUE THREAD

**Issue by edgarbelda** [AquaticInformatics/aquarius-field-data-framework#45]
I'm improving flowtraker2 plugin and I want to access to Uncertainty property to add or modify the value.
Is it possible?
![chrome_2019-02-27_18-23-08](https://user-images.githubusercontent.com/14314396/53509755-c5e6a300-3abc-11e9-9054-b2a7a45361bc.png)

**Comment by DougSchmidt-AI** [comment]
Hi Edgar.

The framework currently doesn't support the importing of discharge uncertainty values, so it isn't possible at the moment.

You're correct in assuming that it should be possible, and you're not the first to ask for it, but we'll need to wait for a new AQTS release to add this property to the `DischargeActivity` DTO.

I've made the development team aware of your request (adding it to the vote count for the existing request).

**Comment by edgarbelda** [comment]
Thank you for your reply. I will keep an eye out for updates. 
Regards
