### ISSUE TITLE
Creating a Visit with Aquarius.Client

### ISSUE THREAD

**Issue by edgarbelda** [AquaticInformatics/aquarius-field-data-framework#51]
I'm trying to create a visit with Aquarius.Client and I don't know if is possible.
I know it's possible do it by plugin but I would like to create an application to import several visits from different files.
Something like this:
```
                var request = new PostFieldVisit();
                //Add some stuff
                var response = _client.Provisioning.Post(request);
```
Thank you in advance.

Regards

**Comment by DougSchmidt-AI** [comment]
Whoops. Sorry for the slow response.

All the field visit data needs to be imported through some sort of plugin (whether one the plugins we provide on our GitHub pages, or one you write yourself).

The [Acquisition.PostVisitFile request DTO](https://github.com/AquaticInformatics/aquarius-sdk-net/blob/develop/src/Aquarius.Client/TimeSeries/Client/ServiceModels/Acquisition.cs#L273) is the one request permitted to create field visit data using a public API.

The Springboard HTML UI uses a private API (not one of the `/Provisioning/v1`, `/Acquisition/v2`, or `/Publish/v2` routes) to create visit data in the browser. But that API can and has changed drastically from release to release. So it isn't anything made public at this time.

It can be a frustrating limitation, for sure.

Is there particular data you are finding difficult to bring in using a plugin?

**Comment by edgarbelda** [comment]
Don't worry. I'm also sorry for the slow response, but last week I was offline.
Finally I decided to create an application and a plugin to import several files at the same time. You showed me something similar in issue #49.
Thanks you very much.

Regards

**Comment by DougSchmidt-AI** [comment]
@edgarbelda I've been busy behind the scenes last week, coding up some enhancements to work around a few of the existing limitation of the field data framework.

These tools were just publicly released today, so expect some bugs along the way, but you may find a few of the [v18.4.7 release assets](https://github.com/AquaticInformatics/aquarius-field-data-framework/releases/tag/v18.4.7) useful to you. I'm trying to ensure that the documentation for these tools is self-contained and clear, so your feedback is welcome.

There are 3 new additions to this release (which require AQTS 2018.4 to work, I can't recall which version KV is using at the moment):
- The [JSON field data plugin](https://github.com/AquaticInformatics/aquarius-field-data-framework/blob/master/src/JsonFieldData/Readme.md) can read any JSON file saved from the **PluginTester.exe** tool. This JSON format ii capable of representing all possible field visit activity types supported by the framework.
- The [FieldVisitHotFolderService.exe tool](https://github.com/AquaticInformatics/aquarius-field-data-framework/blob/master/src/FieldVisitHotFolderService/Readme.md) works in conjunction with the JSON plugin, to parse field visit files locally into memory, and then only uploading the new visits to AQTS. This works around the `Saving parsed data would result in duplicates` error, by just skipping the upload of a visit if a location already has an existing visit on the same day.
- The [MultiFile plugin](https://github.com/AquaticInformatics/aquarius-field-data-framework/blob/master/src/MultiFile/Readme.md) is a plugin you can install on the AQTS app server, that works around the `Saving parsed data would result in duplicates` error in a different way. This plugin will accept a ZIP archive of files supported by other plugins. So you could create a ZIP file with a FlowTracker2 measurement from Tuesday and a StageDischargeReadings CSV file with Tuesday readings, and upload that ZIP file to bring in both files at once, into a single Tuesday visit with the merged results.

**Comment by edgarbelda** [comment]
Very interesting information. You developed a lot of improvements.
KVI is using 18.4.80  on one server and 17.4.40 on another. I can check the changes on the update server.
If I have any possible questions I'll write to you.
Thank you for letting me know.
